### ISSUE TITLE
AvionDb Roadmap April-May-Beyond [Draft]

### ISSUE THREAD

**Issue by vaultec81** [dappkit/aviondb#10]
## Roadmap
**Within Next two months**
- [ ] Exposing pubsub channel to orbit-db-store interface
    - [ ] Secure, authenticated pubsub (Aviondb specific, or orbitdb specific?)
    - [ ] Non Identity based authentication. Tokens, symmetric keys, 3rd party oauth etc. Goes along with custom access controller.
- [ ] Plugins. Non essential additions for authentication, data manipulation, secondary-higher level Peer-To-Peer communications.
- [ ] Custom access controller.

**Two months and beyond**
- [ ] Store (Collection) Sharding
- [ ] File Management Support (#5)

See supporting issues
[AvionDb feature list](https://github.com/dappkit/aviondb/issues/8)
[Orbit-db feature requirements](https://github.com/dappkit/aviondb/issues/7)

**Comment by 0zAND1z** [comment]
Is there a release date available for an HTTP REST API?

Would love to test them for some of the apps where Mongo is being used.

**Comment by vasa-develop** [comment]
@0zAND1z I can pick this up after 3 July. I'm not sure about the release date though.

**Comment by SteveGremory** [comment]
> Is there a release date available for an HTTP REST API?
> 
> Would love to test them for some of the apps where Mongo is being used.
> 
> Cc @vasa-develop

I am making that sorta thing
